{
    "Service": "/KNPL_TSS/Services/com_knpl_tss.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/KNPL_TSS/Actions/Service/InitializeOnlineUser.action",
    "OnFailure": "/KNPL_TSS/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}