{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/KNPL_TSS/Actions/Service/InitializeOnlineFailureMessage.action",
	"OnSuccess": "/KNPL_TSS/Rules/RESTuserLoginDataUpdate.js",
	"ShowActivityIndicator": true,
	"Service": "/KNPL_TSS/Services/com_knpl_tss_User.service"
}