{
	"_Type": "Action.Type.Filter",
	"Filterable": "#Page:ProductDefectSubCategory/#Control:SectionedTable0",
	"PageToOpen": "/KNPL_TSS/Pages/ProductDefectSubCategoryFilter.page",
	"ModalPageFullscreen": false
}