{
	"_Type": "Action.Type.Filter",
	"Filterable": "#Page:ProductDefectCategory/#Control:SectionedTable0",
	"PageToOpen": "/KNPL_TSS/Pages/ProductDefectCategoryFilter.page",
	"ModalPageFullscreen": false
}