{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "RESTupdateUserLogReport"
	},
	"OnFailure": "/KNPL_TSS/Actions/UpdateUserLogDateFailureMessage.action",
	"Target": {
		"Service": "/KNPL_TSS/Services/com_knpl_tss_User.service",
		"Path": "/KNPL_TSS/Rules/GetLogEntitySet.js",
		"RequestProperties": {
			"Method": "PUT",
			"Body": {
				"appVersion": "/KNPL_TSS/Globals/AppDefinition_Version.global"
			}
		}
	}
}