{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "UpdateUserLogFaildMessage"
	},
	"Message": "#ActionResults:RESTUpdateUserLog/error",
	"NumberOfLines": 3,
	"Duration": 3,
	"Icon": "sap-icon://message-error"
}